"""Initial migration

Revision ID: 128af0e500a5
Revises: 04cc7daffc4b
Create Date: 2026-02-21 14:03:11.978969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128af0e500a5'
down_revision: Union[str, Sequence[str], None] = '04cc7daffc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_vector_ivfflat'), table_name='document_chunks', postgresql_ops={'embedding_vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_embedding_vector_ivfflat'), 'document_chunks', ['embedding_vector'], unique=False, postgresql_ops={'embedding_vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
