"""initial

Revision ID: 33d1895b7df9
Revises: 
Create Date: 2026-03-03 18:54:47.120743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d1895b7df9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Гарантируем наличие pgvector
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('interest', 'strength', 'subject', 'career', name='tagtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_index(op.f('ix_tags_title'), 'tags', ['title'], unique=False)
    op.create_index(op.f('ix_tags_type'), 'tags', ['type'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_universities_city'), 'universities', ['city'], unique=False)
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('applicant', 'admin', 'superadmin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.Enum('admission_rules', 'fee_table', 'deadlines', 'other', name='documenttype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('received_from', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_university_id'), 'documents', ['university_id'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.Enum('ru', 'kg', 'en', 'tr', name='language'), nullable=False),
    sa.Column('study_form', sa.Enum('full_time', 'part_time', name='studyform'), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_is_active'), 'programs', ['is_active'], unique=False)
    op.create_index(op.f('ix_programs_language'), 'programs', ['language'], unique=False)
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_index(op.f('ix_programs_study_form'), 'programs', ['study_form'], unique=False)
    op.create_index(op.f('ix_programs_university_id'), 'programs', ['university_id'], unique=False)
    op.create_index('ix_programs_university_lang_form_active', 'programs', ['university_id', 'language', 'study_form', 'is_active'], unique=False)
    op.create_table('survey_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ort_score', sa.Integer(), nullable=False),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('language', sa.Enum('ru', 'kg', 'en', 'tr', name='language'), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('needs_dorm', sa.Boolean(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_submissions_user_id'), 'survey_submissions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_vector', Vector(dim=384), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_chunks_doc_chunk_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_doc_chunks_doc_pages', 'document_chunks', ['document_id', 'page_start', 'page_end'], unique=False)
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('program_admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ort_min_score', sa.Integer(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deadlines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('source_page_start', sa.Integer(), nullable=True),
    sa.Column('source_page_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'year', name='uq_program_adm_program_year')
    )
    op.create_index('ix_program_adm_program_year', 'program_admissions', ['program_id', 'year'], unique=False)
    op.create_index('ix_program_adm_year_ort', 'program_admissions', ['year', 'ort_min_score'], unique=False)
    op.create_index(op.f('ix_program_admissions_ort_min_score'), 'program_admissions', ['ort_min_score'], unique=False)
    op.create_index(op.f('ix_program_admissions_program_id'), 'program_admissions', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_admissions_source_document_id'), 'program_admissions', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_program_admissions_year'), 'program_admissions', ['year'], unique=False)
    op.create_table('program_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('contract_fee', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('KGS', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('source_page_start', sa.Integer(), nullable=True),
    sa.Column('source_page_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_program_fee_program_year', 'program_fees', ['program_id', 'year'], unique=False)
    op.create_index('ix_program_fee_year_currency', 'program_fees', ['year', 'currency'], unique=False)
    op.create_index(op.f('ix_program_fees_name'), 'program_fees', ['name'], unique=False)
    op.create_index(op.f('ix_program_fees_program_id'), 'program_fees', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_fees_source_document_id'), 'program_fees', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_program_fees_year'), 'program_fees', ['year'], unique=False)
    op.create_table('program_tags',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('program_id', 'tag_id')
    )
    op.create_index('ix_program_tags_tag', 'program_tags', ['tag_id'], unique=False)
    op.create_table('saved_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_saved_user_program')
    )
    op.create_index(op.f('ix_saved_programs_program_id'), 'saved_programs', ['program_id'], unique=False)
    op.create_index(op.f('ix_saved_programs_user_id'), 'saved_programs', ['user_id'], unique=False)
    op.create_table('submission_tags',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['survey_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('submission_id', 'tag_id')
    )
    op.create_index('ix_submission_tags_tag', 'submission_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_tags_tag', table_name='submission_tags')
    op.drop_table('submission_tags')
    op.drop_index(op.f('ix_saved_programs_user_id'), table_name='saved_programs')
    op.drop_index(op.f('ix_saved_programs_program_id'), table_name='saved_programs')
    op.drop_table('saved_programs')
    op.drop_index('ix_program_tags_tag', table_name='program_tags')
    op.drop_table('program_tags')
    op.drop_index(op.f('ix_program_fees_year'), table_name='program_fees')
    op.drop_index(op.f('ix_program_fees_source_document_id'), table_name='program_fees')
    op.drop_index(op.f('ix_program_fees_program_id'), table_name='program_fees')
    op.drop_index(op.f('ix_program_fees_name'), table_name='program_fees')
    op.drop_index('ix_program_fee_year_currency', table_name='program_fees')
    op.drop_index('ix_program_fee_program_year', table_name='program_fees')
    op.drop_table('program_fees')
    op.drop_index(op.f('ix_program_admissions_year'), table_name='program_admissions')
    op.drop_index(op.f('ix_program_admissions_source_document_id'), table_name='program_admissions')
    op.drop_index(op.f('ix_program_admissions_program_id'), table_name='program_admissions')
    op.drop_index(op.f('ix_program_admissions_ort_min_score'), table_name='program_admissions')
    op.drop_index('ix_program_adm_year_ort', table_name='program_admissions')
    op.drop_index('ix_program_adm_program_year', table_name='program_admissions')
    op.drop_table('program_admissions')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_index('ix_doc_chunks_doc_pages', table_name='document_chunks')
    op.drop_index('ix_doc_chunks_doc_chunk_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_survey_submissions_user_id'), table_name='survey_submissions')
    op.drop_table('survey_submissions')
    op.drop_index('ix_programs_university_lang_form_active', table_name='programs')
    op.drop_index(op.f('ix_programs_university_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_study_form'), table_name='programs')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_language'), table_name='programs')
    op.drop_index(op.f('ix_programs_is_active'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_university_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_city'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_tags_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_title'), table_name='tags')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
