"""init schema

Revision ID: 5c3a5675e688
Revises: b3c130f326c3
Create Date: 2026-02-16 10:28:20.318815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3a5675e688'
down_revision: Union[str, Sequence[str], None] = 'b3c130f326c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_fees', sa.Column('name', sa.String(length=255), nullable=False, server_default=''))
    op.create_index(op.f('ix_program_fees_name'), 'program_fees', ['name'], unique=False)
    # ### end Alembic commands ###
    op.alter_column("program_fees", "name", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_fees_name'), table_name='program_fees')
    op.drop_column('program_fees', 'name')
    # ### end Alembic commands ###
