"""add source_url and received_from to documents

Revision ID: 8131376729f0
Revises: 5c3a5675e688
Create Date: 2026-02-16 14:56:32.585470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8131376729f0'
down_revision: Union[str, Sequence[str], None] = '5c3a5675e688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('received_from', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'received_from')
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
