"""initial

Revision ID: 99f51c528e77
Revises: 20260511_0001
Create Date: 2026-08-28 21:47:21.013158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f51c528e77'
down_revision: Union[str, Sequence[str], None] = '20260511_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tags_slug_key'), 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tags_slug_key'), 'tags', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
