"""some

Revision ID: aef6ffda111d
Revises: 0ce938905e16
Create Date: 2026-02-22 11:39:50.495727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef6ffda111d'
down_revision: Union[str, Sequence[str], None] = '0ce938905e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_submissions', sa.Column('notes', sa.String(length=512), nullable=True))
    op.add_column('survey_submissions', sa.Column('needs_dorm', sa.Boolean(), nullable=True))
    op.add_column('survey_submissions', sa.Column('willing_to_relocate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_submissions', 'willing_to_relocate')
    op.drop_column('survey_submissions', 'needs_dorm')
    op.drop_column('survey_submissions', 'notes')
    # ### end Alembic commands ###
