"""init schema

Revision ID: b3c130f326c3
Revises: da5df1b4841d
Create Date: 2026-02-16 10:23:17.947958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c130f326c3'
down_revision: Union[str, Sequence[str], None] = 'da5df1b4841d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_program_fee_program_year'), 'program_fees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_program_fee_program_year'), 'program_fees', ['program_id', 'year'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
